name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # Adjust to your project's Node.js version

    - name: Install dependencies
      working-directory: Backend
      run: make install

    - name: Run tests
      working-directory: Backend
      run: make test
